{"name": "test_broken", "status": "broken", "statusDetails": {"message": "Exception: oops", "trace": "def test_broken():\n>       raise Exception(\"oops\")\nE       Exception: oops\n\ntest35_allure.py:23: Exception"}, "start": 1686725042940, "stop": 1686725042941, "uuid": "c8fb428d-5c75-425b-af39-03740f4c6d30", "historyId": "8974c612d44e33b96c359550af7ae1f4", "testCaseId": "8974c612d44e33b96c359550af7ae1f4", "fullName": "test35_allure#test_broken", "labels": [{"name": "suite", "value": "test35_allure"}, {"name": "host", "value": "LAPTOP-Q5VATU4G"}, {"name": "thread", "value": "28076-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test35_allure"}]}